// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appName => 'DeepTruth';

  @override
  String get tagline => 'In a world of lies, let DeepTruth be your eyes.';

  @override
  String get factCheckTitle => 'Truth Lens';

  @override
  String get factCheckHint => 'Paste news, claim, link, or reel URL...';

  @override
  String get analyzeButton => 'Analyze';

  @override
  String get analyzing => 'Analyzing...';

  @override
  String get verdictTrue => 'TRUE';

  @override
  String get verdictFalse => 'FALSE';

  @override
  String get verdictMisleading => 'MISLEADING';

  @override
  String get verdictUnverified => 'UNVERIFIED';

  @override
  String get truthScore => 'Truth Score';

  @override
  String get manipulationScore => 'Manipulation Score';

  @override
  String get missingContext => 'Missing Context';

  @override
  String get sources => 'Sources';

  @override
  String get manipulationTactics => 'Manipulation Tactics';

  @override
  String get personalImpact => 'Personal Impact';

  @override
  String get downloadReport => 'Download Report';

  @override
  String get shareReport => 'Share Report';

  @override
  String get trustFeed => 'Trust Feed';

  @override
  String get reelIQ => 'ReelIQ';

  @override
  String get traceIQ => 'TraceIQ';

  @override
  String get askIQ => 'AskIQ';

  @override
  String get streak => 'Streak';

  @override
  String get home => 'Home';

  @override
  String streakDays(int count) {
    return '$count day streak';
  }

  @override
  String get rank => 'Rank';

  @override
  String nextRank(int days) {
    return 'Next rank in $days days';
  }

  @override
  String get emailCheck => 'Email Breach Check';

  @override
  String get phoneCheck => 'Phone Lookup';

  @override
  String get usernameCheck => 'Username Search';

  @override
  String get websiteCheck => 'Website WHOIS';

  @override
  String get ipCheck => 'IP Lookup';

  @override
  String get imageSearch => 'Reverse Image Search';

  @override
  String get osintDisclaimer => 'Data from public sources only. Results may be incomplete.';

  @override
  String get investigateYourself => 'Investigate Yourself First';

  @override
  String get typeMessage => 'Ask anything...';

  @override
  String get sources2 => 'Sources';

  @override
  String get relatedFacts => 'Related Facts';

  @override
  String get noInternet => 'No internet connection';

  @override
  String get tryAgain => 'Try Again';

  @override
  String get loading => 'Loading...';

  @override
  String get error => 'Something went wrong';

  @override
  String get errorRetry => 'Something went wrong. Pull to refresh.';

  @override
  String get dailyReality => 'Today\'s Reality Check';

  @override
  String get trendingChecks => 'Trending Checks';

  @override
  String get quickActions => 'Quick Actions';

  @override
  String get checkNews => 'Check a news article';

  @override
  String get checkReel => 'Check a reel/video';

  @override
  String get checkWebsite => 'Verify a website';

  @override
  String get reportId => 'Report ID';

  @override
  String get generatedBy => 'Generated by DeepTruth';

  @override
  String get dataOnly => 'Data only. Conclusions are yours to make.';

  @override
  String get scanToVerify => 'Scan to verify this report\'s authenticity';

  @override
  String osintRateLimit(int limit) {
    return 'Daily limit reached ($limit lookups/day). Resets tomorrow.';
  }

  @override
  String get analysisUnavailable => 'Analysis temporarily unavailable. Please try again.';

  @override
  String get offlineMode => 'Offline — showing cached data';

  @override
  String get leaderboard => 'Leaderboard';

  @override
  String get globalRanking => 'Global Ranking';

  @override
  String get streakFreezeUsed => 'Streak freeze used for this month';

  @override
  String get streakFreeze => 'Use Streak Freeze';

  @override
  String get achievements => 'Achievements';
}
